---
root: true
parser: '@typescript-eslint/parser'
env:
  node: true
  es2020: true
settings:
  react:
    version: 'detect'
plugins:
  - react
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier
rules:
  "react/display-name": "off"
